import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/styles.scss";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import StoreProvider from "@/redux/Providers";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
        <header className="">
          <div className="header-inner mx-auto flex justify-between items-center">
            <h1 className="text-2xl font-bold">Video Editor</h1>
          </div>
        </header>
          {children}
        </StoreProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
